### ISSUE TITLE
Jar не едет на linux

### ISSUE THREAD

**Issue by IS2511** [IgorTimofeev/OpenComputersVM#2]
Так как мне лень думать и проблема скорее всего не на мой стороне, я просто скину все сюда и буду ждать чуда.

Окружение: `Linux parrot 4.14.0-parrot2-amd64 #1 SMP Parrot 4.14.2-1parrot2 (2017-12-05) x86_64 GNU/Linux`, по сути это Debian.
Команда: `jdk1.8.0_191/bin/./java -jar OpenComputersVM.jar`
Лог:
`Loading font Font[name=Minecraft Regular, family=Minecraft, style=Regular, size=10.0]
Loading config from /home/is2511/OpenComputersVM/Config6.json
Generating new machine...
Copying OpenOS sources...`
<A lot of unzipping>
`javafx.fxml.LoadException: 
file:/home/is2511/OpenComputersVM.jar!/vm/computer/Window.fxml:20

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at vm.computer.Machine.fromJSONObject(Machine.java:98)
	at vm.computer.Machine.generate(Machine.java:314)
	at vm.Main.start(Main.java:44)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:518)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:421)
	at vm.computer.Player.fromResource(Player.java:33)
	at vm.computer.Player.<init>(Player.java:23)
	at vm.computer.Machine.<init>(Machine.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:927)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971)
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	... 14 more
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:474)
	... 30 more`

Лог длинный, примерно на 7-ой строчке заканчивается интересное и полезное.
ИМХО что-то не так с интерфейсом.

Да прибудет фикс!

**Comment by IgorTimofeev** [comment]
Ошибка из-за невозможности воспроизвести музло по какой-то там мяу-причине в JavaFX-фреймворке. Возможно, из-за некорректности строкового пути для медиа-данных, который по какой-то причине отличается на лине. Увы, я не разбираться в этом, да и линя для "потестить" свободного нет, прсти, золотце. Могу лишь дать котика:

![0urdekyxmya](https://user-images.githubusercontent.com/11760002/50379758-50e19200-0663-11e9-8c49-ef0fc4c3cf2e.jpg)

**Comment by TC1061** [comment]
У меня всё завелось, проблем нет.

**Comment by IgorTimofeev** [comment]
@TC1061 Угу, лимит не выставлял. А что за повтор клавиш?

**Comment by IS2511** [comment]
@IgorTimofeev Теперь работает (вроде ничего не изменял, разве что jre обновил). Но есть другие крашы, создать новый issuse? Или тут писать? (Скорее всего относится к линуксу все)

**Comment by IgorTimofeev** [comment]
@IS2511 Та не надо, я все равно этот эмуль по приколу написал. Если случилось чет прям критическое и легко-фиксабельное, то го. А подстраиваться под системные тонкости, выискивая злоебучие несовместимости оч впадлу, да и не смогу я

**Comment by IS2511** [comment]
Тогда закрываю
